openapi: 3.0.0
x-stoplight:
  id: shyvbdru80a8i
info:
  title: tutorial-api
  version: '1.0'
  description: backend tutorial
servers:
  - url: 'http://localhost:3000'
paths:
  /contents:
    get:
      summary: コンテンツ一覧の取得
      operationId: get-Contents
      tags:
        - Content
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Content'
          headers: {}
      x-stoplight:
        id: jaxhnr1gv9qxs
      x-internal: true
      parameters: []
    post:
      summary: コンテンツの作成
      operationId: post-content
      tags:
        - Content
      responses:
        '201':
          description: Content Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
              examples: {}
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostContentRequest'
            examples: {}
      x-stoplight:
        id: r1wwt8ur8axks
      x-internal: true
      description: Post the necessary fields for the API to create a new content.
    parameters: []
  /contents/bulk-delete:
    post:
      summary: 複数コンテンツの一括削除
      operationId: delete-multiple-contents
      tags:
        - Content
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BulkDeleteResponse'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BulkDeleteRequest'
      x-stoplight:
        id: bulk-delete-contents
      x-internal: true
      description: 指定されたIDの複数コンテンツを一括削除します。
    parameters: []
  '/contents/{id}':
    parameters:
      - schema:
          type: number
        name: id
        in: path
        required: true
    get:
      summary: コンテンツの取得
      operationId: get-contents-contentsId
      tags:
        - Content
      responses:
        '200':
          description: Content Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
              examples:
                Example 1:
                  value:
                    id: 3
                    title: Hello Title
                    body: Hello Body
                    createDate: '2019-08-24'
                    updateDate: '2019-08-24'
          headers: {}
      x-stoplight:
        id: nnavtavn82qnu
      x-internal: true
    put:
      summary: コンテンツの更新
      operationId: put-contents-contentId
      tags:
        - Content
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Content'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateContentRequest'
      x-stoplight:
        id: gpzpzxftidc24
      x-internal: true
    delete:
      summary: コンテンツの削除
      operationId: delete-contents-contentId
      tags:
        - Content
      responses:
        '204':
          description: No Content
      x-stoplight:
        id: djs9gmof7n97r
      x-internal: true
components:
  schemas:
    Content:
      title: Content
      type: object
      x-examples: {}
      x-stoplight:
        id: l68i6i5ij90u2
      x-internal: true
      required:
        - id
        - title
        - body
      properties:
        id:
          type: integer
          description: Unique identifier for the given content.
          x-stoplight:
            id: 0n9dbuncumt4n
          example: 1
        title:
          type: string
          x-stoplight:
            id: djogm4kxo93ag
          description: コンテンツのタイトル
          maxLength: 100
          example: Book Title
        body:
          type: string
          x-stoplight:
            id: dakrjnx4emd7r
          description: コンテンツのボディ
          maxLength: 2000
          example: Book Body
        createdAt:
          type: string
          format: date
          description: The date that the content was created.
          x-stoplight:
            id: qet6outkt29d5
        updatedAt:
          type: string
          format: date
          x-stoplight:
            id: afyvsy57w429s
          description: The date that the content was updated11
    PostContentRequest:
      title: PostContentRequest
      type: object
      x-stoplight:
        id: co2wm6xdqyxg9
      x-internal: true
      properties:
        title:
          type: string
          x-stoplight:
            id: iid6fzq7aeqs6
          example: Hello Title
        body:
          type: string
          x-stoplight:
            id: ir6w0w56pgulz
          example: Hello Body
    UpdateContentRequest:
      title: UpdateContentRequest
      type: object
      x-examples:
        Example 1:
          title: Update Title
          body: Update Body
      x-internal: true
      properties:
        title:
          type: string
          x-stoplight:
            id: gku306wepue7o
          example: Update Title
        body:
          type: string
          x-stoplight:
            id: umaunx6atkv6f
          example: Update Body
    BulkDeleteRequest:
      title: BulkDeleteRequest
      type: object
      x-internal: true
      required:
        - ids
      properties:
        ids:
          type: array
          items:
            type: string
          description: 削除対象のコンテンツIDの配列
          example: ["1", "2", "3"]
    BulkDeleteResponse:
      title: BulkDeleteResponse
      type: object
      x-internal: true
      properties:
        deletedCount:
          type: integer
          description: 削除されたコンテンツの件数
          example: 2
        deletedIds:
          type: array
          items:
            type: integer
          description: 削除されたコンテンツのIDの配列
          example: [1, 2]
        message:
          type: string
          description: 削除結果のメッセージ
          example: "2件のコンテンツを削除しました"
  securitySchemes: {}
x-internal: true
tags:
  - name: Content
